### ISSUE TITLE
.and_sample(n) does't work as expected

### ISSUE THREAD

**Issue by vochicong** [piotrmurach/rspec-benchmark#8]
### Describe the problem

.and_sample(n) does't work as expected as `n < 3`

### Steps to reproduce the problem

See https://github.com/vochicong/csv_step_importer_sample/blob/master/spec/performance/book_importer_spec.rb#L15

### Actual behaviour

- `.and_sample(n)` doesn't work for n = 1, 2, it will run 3 times
- `.and_sample(-1)` seems to run once, but sometimes it seems to run 3 times.

### Expected behaviour

- Default sample to be 1
- `.and_sample(n)` work for `n < 3`

### Describe your environment

* OS version: CircleCI
* Ruby version: 2.4
* RSpec version: 3.8
* RSpec::Benchmark version: 0.3

**Comment by piotrmurach** [comment]
Hi Cong,

Thanks for using the gem and reporting this issue!

This issue should be fixed on master branch. Can you point your gem dependency source directly at this repository? I will release shortly. One thing I'm planning to do is to change `and_sample` to be named `sample` instead. This is confusing for anyone using compound rspec matchers.

I don't think having sample size to be `1` is an optimal default for most cases. One measurement is not enough to establish benchmark for any case, you want to run it few times to have more accurate measurement and thus prevent your tests from being flaky and failing for no reason, because the Ruby vm took longer to garbage collect or warmup. You want to minimize the effect of outliers.

**Comment by vochicong** [comment]
Thank you.

I think that I can wait until you release a new version. And `sample` sounds better than `and_sample`.

I understand that a default sample size of `1` is not good for a benchmark,but it won't surprise a 1st time user like me.

It'd be better if one can set a default sample size in a config file so that one doesn't need to repeatedly specify them same sample size in RSpec.

**Comment by piotrmurach** [comment]
On reflection, I've changed the default sample size to be `1` and anything below that value will raise an error.

**Comment by piotrmurach** [comment]
Released `v0.4.0` with the new api.

**Comment by vochicong** [comment]
Thank you @piotrmurach
